export const START_FETCH_NEWS = 'START_FETCH_NEWS';
export const SUCCESS_FETCH_NEWS = 'SUCCESS_FETCH_NEWS';
export const ERROR_FETCH_NEWS = 'ERROR_FETCH_NEWS';

export const START_FETCH_TAGS = 'START_FETCH_TAGS';
export const SUCCESS_FETCH_TAGS = 'SUCCESS_FETCH_TAGS';
export const ERROR_FETCH_TAGS = 'ERROR_FETCH_TAGS';
